# Generated by Django 5.2.4 on 2026-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='language',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
