# Generated by Django 5.2.4 on 2026-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_spot_mood_spot_purpose_spot_time_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='time_axis',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
