# Generated by Django 5.2.4 on 2026-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_remove_spot_image_url_spot_image_alter_favorite_spot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='time_axis',
            field=models.CharField(blank=True, max_length=50, verbose_name='時間軸'),
        ),
    ]
