# Generated by Django 5.2.4 on 2026-02-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_spot_time_axis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='start_at',
        ),
    ]
