# Generated by Django 5.2.4 on 2026-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0010_remove_spot_end_at_remove_spot_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='business_days',
            field=models.CharField(blank=True, max_length=100, verbose_name='営業日'),
        ),
        migrations.AddField(
            model_name='spot',
            name='business_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='営業時間'),
        ),
        migrations.AddField(
            model_name='spot',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='spot',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='体験時間'),
        ),
        migrations.AddField(
            model_name='spot',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, verbose_name='検索ワード'),
        ),
        migrations.AddField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='駐車場あり'),
        ),
        migrations.AddField(
            model_name='spot',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='spot',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, verbose_name='価格帯'),
        ),
        migrations.AddField(
            model_name='spot',
            name='website',
            field=models.URLField(blank=True, verbose_name='参考サイト'),
        ),
    ]
