# Generated by Django 5.2.4 on 2026-02-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0012_remove_spot_business_hours_remove_spot_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='business_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
